logfile: './topi-local.log'
express:
  name: 'express'
  version: 'local'
  express_port: 5104
mongo:
  name: 'mongo'
  topi_db:
    instance: { type: 'host_port', host: 127.0.0.1, port: 27017 }
    dbname: topi

